
name: CI
on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v2
       
       - name: Echo Version
         env:
          VERSION: ${{ github.event.inputs.version }}
         run: |
          echo "Version: $VERSION"
         # 获取对应发布版本的制品
       - name: Download Artifact
         uses: actions/download-artifact@v3
         with:
          version: "tags/${{ github.event.inputs.version }}"
          # 指定存放制品的压缩包
          file: "assets.zip"
          # 这里需要CD Workflow中准备工作里的Github Personal Access Token
          token: ${{ secrets.GITHUB_TOKEN }}
