name: Deployment
on:
  push:
    branches: [ master ]
jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 输出我们输入的version值
      - name: Echo Version
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Version: $VERSION"
      
      - name: Read Version
        # 读取出来的值会放在steps.[id].outputs.value供其他步骤step读取
        id: version
        uses: ashley-taylor/read-json-property-action@v1.0
        with:
          path: ./package.json
          property: version


     
