name: Deployment
on:
  push:
    branches: [ master ]
jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # 输出我们输入的version值
      - name: Echo Version
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          echo "Version: $VERSION"
     
